---
name: Test container builds

"on":
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version:
          - 0.14.7
          - 1.2.4
          - 1.2.5
        ruby_version:
          - 3.1.2
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.terraform_version }}-edge

      - name: Test
        run: docker run --rm -v "$(pwd)/examples/check-container":/usr/action ghcr.io/${{ github.repository }}:${{ matrix.terraform_version }}-edge "converge"

      - name: Build and Export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            TERRAFORM_VERSION=${{ matrix.terraform_version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.terraform_version }}-edge
